### ISSUE TITLE
Color contrast did not match

### ISSUE THREAD

**Issue by Seliya123** [Seliya123/E-challan-System#11]
As you can see in the footer the text is in the dark color which is invisible so can you please change the color into light.

![aaa](https://user-images.githubusercontent.com/81378815/118253834-1a25a400-b4ca-11eb-95f8-22c00e3e4235.png)

**Comment by manish287** [comment]
![footer](https://user-images.githubusercontent.com/81401244/118259062-64118880-b4d0-11eb-9f82-876f8f68b1b4.JPG)
Done
