### ISSUE TITLE
Challan Login Form css

### ISSUE THREAD

**Issue by susan-grg** [Seliya123/E-challan-System#12]
The css of the form is not made properly. Make the css better and align the item in center.
![Screenshot (67)](https://user-images.githubusercontent.com/81401337/118255385-ecd9f580-b4cb-11eb-816f-fa0a169587d4.png)

**Comment by subodh633** [comment]
![image](https://user-images.githubusercontent.com/81404416/118385899-dd28f100-b632-11eb-8b48-84e64b207c60.png)
I have solved this issue.
