### ISSUE TITLE
Improper font color in login page

### ISSUE THREAD

**Issue by Seliya123** [Seliya123/E-challan-System#13]
As you can see in the first image 'return to' doesn't seems to be visible so please make it visible by changing the color.
![cc](https://user-images.githubusercontent.com/81378815/118255477-0d09b480-b4cc-11eb-8de6-9da0bba9f593.png)
![bbb](https://user-images.githubusercontent.com/81378815/118255457-067b3d00-b4cc-11eb-88f8-c980c0688d38.png)

**Comment by suyash37** [comment]
![Screenshot (1017)](https://user-images.githubusercontent.com/81401197/118385866-90ddb100-b632-11eb-8ec3-2da550f51390.png)

**Comment by suyash37** [comment]
issue closed
