### ISSUE TITLE
Challan page nav Button

### ISSUE THREAD

**Issue by susan-grg** [Seliya123/E-challan-System#14]
The nav button for logout and admin is not proper. Correct their css positioning.
![image](https://user-images.githubusercontent.com/81401337/118385876-b2d73380-b632-11eb-9b95-85783d00692e.png)

**Comment by manish287** [comment]
![00002](https://user-images.githubusercontent.com/81401244/118385936-2bd68b00-b633-11eb-83d9-bf1e91b708f8.JPG)
Done
