### ISSUE TITLE
Improper management of navigation bar

### ISSUE THREAD

**Issue by Seliya123** [Seliya123/E-challan-System#3]
When you are in Home page a box is seen in the navigation bar home page but when we go in other pages then there is no box around the selected pages in navigation bar.
![1](https://user-images.githubusercontent.com/81378815/114312163-6c615700-9b11-11eb-919e-441c64563a94.png)
![2](https://user-images.githubusercontent.com/81378815/114312167-6e2b1a80-9b11-11eb-9bde-c2d4ff36af8c.png)

**Comment by manish287** [comment]
The issue has been fixed.

**Comment by Seliya123** [comment]
Okay push the updated file in the Git hub.
