### ISSUE TITLE
Improper management of Navigation bar 

### ISSUE THREAD

**Issue by Seliya123** [Seliya123/E-challan-System#5]
When you are in Home page a box is seen in the navigation bar home page but when we go in other pages then there is no box around the selected pages in navigation bar.
![1](https://user-images.githubusercontent.com/81378815/114812521-ea528600-9dcf-11eb-966a-cc62662e724a.png)
![2](https://user-images.githubusercontent.com/81378815/114812568-fd655600-9dcf-11eb-9850-44b595f481fa.png)

**Comment by manish287** [comment]
Solve
![1](https://user-images.githubusercontent.com/81401244/114955447-728e6500-9e7c-11eb-8ac7-bb25a0ea48c8.JPG)
![2](https://user-images.githubusercontent.com/81401244/114955452-7621ec00-9e7c-11eb-8c2b-7b3ea8ff031d.JPG)
