### ISSUE TITLE
Slider Image

### ISSUE THREAD

**Issue by susan-grg** [Seliya123/E-challan-System#6]
The slider image is not working. Please add some css and js to the file so that it functions properly and looks attractive.

![Screenshot (4)](https://user-images.githubusercontent.com/81401337/114975678-628a7b80-9ea4-11eb-8971-2e69dc18424b.png)

**Comment by suyash37** [comment]
I have corrected this issue.
![image](https://user-images.githubusercontent.com/81401197/115020496-689b4f00-9eda-11eb-829e-523663258f82.png)
