### ISSUE TITLE
Sign in button

### ISSUE THREAD

**Issue by susan-grg** [Seliya123/E-challan-System#7]
The Sign in button looks so unattractive. Please give it some css to make it look more atrractive.

![Screenshot (4)](https://user-images.githubusercontent.com/81401337/114975869-aed5bb80-9ea4-11eb-887f-a3c8305f9914.png)

**Comment by subodh633** [comment]
Solved
![screenshot(245)](https://user-images.githubusercontent.com/81404416/115021996-781b9780-9edc-11eb-94c4-b8a403fdff54.jpg)
