### ISSUE TITLE
Challan Page

### ISSUE THREAD

**Issue by susan-grg** [Seliya123/E-challan-System#8]
The background image behind the text looks a bit awful and unattractive and it seems to not match with the other sections of the page. It will be nice if you put a solid color image instead of that image, which looks attractive.

![Screenshot 2021-05-11 152217](https://user-images.githubusercontent.com/81401337/117794673-2c56d680-b26d-11eb-8aaa-732d988fdde8.png)

**Comment by manish287** [comment]
![2](https://user-images.githubusercontent.com/81401244/117799050-7772e880-b271-11eb-8770-f420bbd51309.JPG)
Is that Ok?

**Comment by susan-grg** [comment]
seem better and attractive than before, if you can u can check other colors as well or you can leave it like this.

**Comment by manish287** [comment]
I will leave it like this.
